name: Extend config
keywords: ['extend config', 'extend reciple.yml', 'config extensions', 'extends', 'reciple.yml']
content: |-
  • Use the `extends` property to extend another yml config file
  • Run reciple and use the extended config

  ```yml
  # reciple.test.yml
  extends: ./reciple.yml

  # override properties from reciple.yml
  token: env:TEST_TOKEN

  applicationCommandRegister:
    allowRegisterGlobally: false
    allowRegisterToGuilds: true
  ```
  ```
  npx reciple -c ./reciple.test.yml
  ```