id: sweepers-config
name: Sweepers config
keywords: ['cache sweepers', 'clean cache', 'clear cache', 'sweeping caches']
content: |-
  • Create a js file that contains your sweeper options
  • Use the `--sweepers-config <file>` flag

  ```js
  // sweepers.js
  import { Options } from 'discord.js';

  export default {
    ...Options.DefaultSweeperSettings,
    messages: {
      interval: 3600, // Every hour...
      lifetime: 1800,	// Remove messages older than 30 minutes.
      },
    users: {
      interval: 3600, // Every hour...
      filter: user => user.bot && user.id !== client.user.id, // Remove all bots.
      }
  }
  ```
  ```
  npx reciple --sweepers-config sweepers.js
  ```